# Import required libraries

In [1]:
import pandas
import numpy

# Read Data

In [2]:
data = pandas.read_csv('Loan.csv')
data.head()

Gender  Married  Dependents  Self_Employed  ApplicantIncome  \
0       1        1           0              0             2333   
1       1        1           3              0             3036   
2       1        1           2              0             3073   
3       1        1           0              1             2600   
4       1        1           1              0             5955   

   CoapplicantIncome  LoanAmount  Loan_Amount_Term  Property_Area  Loan_Status  
0             1516.0          95               360              2            1  
1             2504.0         158               360              0            0  
2             8106.0         200               360              2            1  
3             3500.0         115                 0              2            1  
4             5625.0         315               360              2            1

# Dividing the data into dependent and independent variables

In [3]:
Y = data.Loan_Status
X = data.drop(columns = ['Loan_Status'])

# Splitting data into training set and testing set

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((141, 9), (36, 9), (141,), (36,))

# Standardize of a dataset

https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html

In [12]:
from sklearn.preprocessing import StandardScaler
SS = StandardScaler()
X_train = SS.fit_transform(X_train)
X_test = SS.fit_transform(X_test)
X_train

array([[ 0.5636994 ,  0.77606232,  1.29840563, ..., -0.2051452 ,
         0.28824019,  1.17564133],
       [-1.77399516,  0.77606232, -0.75861902, ..., -0.08153207,
         0.28824019, -1.11077836],
       [-1.77399516, -1.28855631, -0.75861902, ..., -0.2146539 ,
         0.28824019,  1.17564133],
       ...,
       [ 0.5636994 , -1.28855631, -0.75861902, ..., -0.32875833,
         1.8513889 ,  1.17564133],
       [ 0.5636994 ,  0.77606232, -0.75861902, ..., -0.15760169,
         0.28824019, -1.11077836],
       [ 0.5636994 ,  0.77606232, -0.75861902, ...,  1.67757789,
         0.28824019,  1.17564133]])

# Import GaussianNB from sklearn library and fit into it

In [13]:
from sklearn.naive_bayes import GaussianNB

model = GaussianNB()

In [14]:
model.fit(X_train, y_train)

GaussianNB()

# Predict the outcomes of testing data

In [15]:
y_pred = model.predict(X_test)

In [16]:
y_pred

array([1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1])

# Printing metrics of the model

In [17]:
from sklearn.metrics import accuracy_score, confusion_matrix

acc = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)
acc, cm

(0.7777777777777778,
 array([[ 2,  6],
        [ 2, 26]]))