# Import all required Libraries¶

In [1]:
import pandas
import numpy

# Read data

In [2]:
data = pandas.read_csv('Titanic.csv')
data.head(10)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   
9           10         1       2   

                                                Name     Sex   Age  \
0                            Braund, Mr. Owen Harris    male  22.0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
2                             Heikkinen, Miss. Laina  female  26.0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
4                           Allen, Mr. William Henry    male  35.0   
5                                   Moran, Mr. James    male   NaN   
6                            McCarthy, Mr. Timothy J    male  54.0   
7                     Palsson, Master. Gosta Leonard    male   2.0   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0   
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0   

             Ticket     Fare  
0         A/5 21171   7.2500  
1          PC 17599  71.2833  
2  STON/O2. 3101282   7.9250  
3            113803  53.1000  
4            373450   8.0500  
5            330877   8.4583  
6             17463  51.8625  
7            349909  21.0750  
8            347742  11.1333  
9            237736  30.0708

# Drop Unnessesary columns from the data

In [3]:
data = data.drop(columns = ['PassengerId', 'Name', 'Ticket'])
data.head(10)

Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500
5         0       3    male   NaN   8.4583
6         0       1    male  54.0  51.8625
7         0       3    male   2.0  21.0750
8         1       3  female  27.0  11.1333
9         1       2  female  14.0  30.0708

# Replacing non numerical values to numerical values

In [4]:
from sklearn.preprocessing import LabelEncoder
le_sex = LabelEncoder()
data['sex'] = le_sex.fit_transform(data['Sex'])
data.head(10)

Survived  Pclass     Sex   Age     Fare  sex
0         0       3    male  22.0   7.2500    1
1         1       1  female  38.0  71.2833    0
2         1       3  female  26.0   7.9250    0
3         1       1  female  35.0  53.1000    0
4         0       3    male  35.0   8.0500    1
5         0       3    male   NaN   8.4583    1
6         0       1    male  54.0  51.8625    1
7         0       3    male   2.0  21.0750    1
8         1       3  female  27.0  11.1333    0
9         1       2  female  14.0  30.0708    0

In [5]:
data = data.drop(columns = ['Sex'])
data.head(10)

Survived  Pclass   Age     Fare  sex
0         0       3  22.0   7.2500    1
1         1       1  38.0  71.2833    0
2         1       3  26.0   7.9250    0
3         1       1  35.0  53.1000    0
4         0       3  35.0   8.0500    1
5         0       3   NaN   8.4583    1
6         0       1  54.0  51.8625    1
7         0       3   2.0  21.0750    1
8         1       3  27.0  11.1333    0
9         1       2  14.0  30.0708    0

# Filling null values with the mean of remaining values in the column

In [6]:
data.Age = data.Age.fillna(data.Age.mean())
data.head(10)

Survived  Pclass        Age     Fare  sex
0         0       3  22.000000   7.2500    1
1         1       1  38.000000  71.2833    0
2         1       3  26.000000   7.9250    0
3         1       1  35.000000  53.1000    0
4         0       3  35.000000   8.0500    1
5         0       3  29.699118   8.4583    1
6         0       1  54.000000  51.8625    1
7         0       3   2.000000  21.0750    1
8         1       3  27.000000  11.1333    0
9         1       2  14.000000  30.0708    0

# Dividing the data into dependent and independent variables

In [7]:
Y = data.Survived
X = data.drop(columns = ['Survived'])
X, Y

(     Pclass        Age     Fare  sex
 0         3  22.000000   7.2500    1
 1         1  38.000000  71.2833    0
 2         3  26.000000   7.9250    0
 3         1  35.000000  53.1000    0
 4         3  35.000000   8.0500    1
 ..      ...        ...      ...  ...
 886       2  27.000000  13.0000    1
 887       1  19.000000  30.0000    0
 888       3  29.699118  23.4500    0
 889       1  26.000000  30.0000    1
 890       3  32.000000   7.7500    1
 
 [891 rows x 4 columns],
 0      0
 1      1
 2      1
 3      1
 4      0
       ..
 886    0
 887    1
 888    0
 889    1
 890    0
 Name: Survived, Length: 891, dtype: int64)

# Splitting data into training data and testing data 

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2)

# Standardize of a dataset

https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html

In [9]:
from sklearn.preprocessing import StandardScaler
SS = StandardScaler()
X_train = SS.fit_transform(X_train)
X_test = SS.fit_transform(X_test)
X_train, X_test

(array([[-1.52295078, -0.02389558, -0.66185417,  0.71980808],
        [ 0.83175271, -1.05388198, -0.25470425,  0.71980808],
        [-0.34559904, -0.02389558, -0.41354299, -1.38925921],
        ...,
        [ 0.83175271, -0.60276399, -0.46405974, -1.38925921],
        [-1.52295078, -0.60276399,  0.3334012 , -1.38925921],
        [-0.34559904,  0.90096265, -0.40047398,  0.71980808]]),
 array([[-4.75423387e-01,  9.09624656e-01, -3.32070411e-01,
          8.10806640e-01],
        [-4.75423387e-01, -3.81837903e-01, -3.32070411e-01,
          8.10806640e-01],
        [ 8.13982466e-01, -1.23545391e-01, -4.37670607e-01,
          8.10806640e-01],
        [ 8.13982466e-01,  1.08841901e-01, -7.91043526e-02,
         -1.23333968e+00],
        [-1.76482924e+00,  2.20108721e+00,  9.92278443e-01,
         -1.23333968e+00],
        [ 8.13982466e-01,  1.08841901e-01, -4.19069535e-01,
          8.10806640e-01],
        [ 8.13982466e-01, -6.40130415e-01, -4.38092667e-01,
          8.10806640e-01],
    

# Import DesicionTreeClassifier from the sklearn library

In [14]:
from sklearn import tree

model = tree.DecisionTreeClassifier()

# Training model by providing the training data into the model

In [15]:
model.fit(X_train, y_train)

DecisionTreeClassifier()

# Training model by providing the training data into the model

In [16]:
y_pred = model.predict(X_test)
y_pred

array([0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0])

# Printing metrics of the model

In [17]:
from sklearn.metrics import accuracy_score

acc = accuracy_score(y_test, y_pred)
acc

0.7262569832402235

In [18]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
cm

array([[78, 32],
       [17, 52]])