# Import all required Libraries

In [1]:
import pandas
import numpy

# Read data

In [2]:
data = pandas.read_csv('Insurance.csv')
data.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years Department  \
0                   3              0     1                      0      sales   
1                   6              0     1                      0      sales   
2                   4              0     1                      0      sales   
3                   5              0     1                      0      sales   
4                   3              0     1                      0      sales   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

# Getting all unique non numerical values in the Columns Department and 

# Salary and Replacing them with numerical values

In [3]:
data.Department.unique()

array(['sales', 'accounting', 'hr', 'technical', 'support', 'management',
       'IT', 'product_mng', 'marketing', 'RandD'], dtype=object)

In [4]:
Department = {'sales': 1, 'accounting': 2, 'hr': 3, 'technical': 4, 'support': 5, 'management': 6, 'IT': 7, 'product_mng': 8, 'marketing': 9, 'RandD': 10}

data.Department = [Department[item] for item in data.Department]
data.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years  Department  \
0                   3              0     1                      0           1   
1                   6              0     1                      0           1   
2                   4              0     1                      0           1   
3                   5              0     1                      0           1   
4                   3              0     1                      0           1   

   salary  
0     low  
1  medium  
2  medium  
3     low  
4     low

In [5]:
data.salary.unique()

array(['low', 'medium', 'high'], dtype=object)

In [6]:
salary = {'low': 1, 'medium': 2, 'high': 3}

data.salary = [salary[item] for item in data.salary]
data.head()

satisfaction_level  last_evaluation  number_project  average_montly_hours  \
0                0.38             0.53               2                   157   
1                0.80             0.86               5                   262   
2                0.11             0.88               7                   272   
3                0.72             0.87               5                   223   
4                0.37             0.52               2                   159   

   time_spend_company  Work_accident  left  promotion_last_5years  Department  \
0                   3              0     1                      0           1   
1                   6              0     1                      0           1   
2                   4              0     1                      0           1   
3                   5              0     1                      0           1   
4                   3              0     1                      0           1   

   salary  
0       1  
1       2  
2       2  
3       1  
4       1

# Dividing the data into dependent and independent variables

In [7]:
Y = data.left
X = data.drop(columns = ['left'])

In [13]:
X, Y

(       satisfaction_level  last_evaluation  number_project  \
 0                    0.38             0.53               2   
 1                    0.80             0.86               5   
 2                    0.11             0.88               7   
 3                    0.72             0.87               5   
 4                    0.37             0.52               2   
 ...                   ...              ...             ...   
 14994                0.40             0.57               2   
 14995                0.37             0.48               2   
 14996                0.37             0.53               2   
 14997                0.11             0.96               6   
 14998                0.37             0.52               2   
 
        average_montly_hours  time_spend_company  Work_accident  \
 0                       157                   3              0   
 1                       262                   6              0   
 2                       272             

In [8]:
X.shape, Y.shape

((14999, 9), (14999,))

# Splitting data into training set and testing set

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((11999, 9), (3000, 9), (11999,), (3000,))

# Standardize of a dataset

https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html

In [11]:
from sklearn.preprocessing import StandardScaler
SS = StandardScaler()
X_train = SS.fit_transform(X_train)
X_test = SS.fit_transform(X_test)

In [12]:
X_train, X_test

(array([[-0.33349846, -0.39986178, -0.66279075, ..., -0.14407333,
         -1.18391481, -0.93816948],
        [ 1.115193  , -0.92577886,  0.15021541, ..., -0.14407333,
          0.94978141, -0.93816948],
        [-0.33349846,  1.6453713 , -0.66279075, ..., -0.14407333,
          0.94978141,  0.63273418],
        ...,
        [-0.33349846, -0.92577886,  0.96322157, ..., -0.14407333,
          0.23854934,  2.20363783],
        [ 0.87374442,  1.52850084,  0.15021541, ..., -0.14407333,
          0.23854934,  0.63273418],
        [-0.21277417, -1.80230732,  0.96322157, ..., -0.14407333,
         -1.18391481,  0.63273418]]),
 array([[-2.01785852,  1.12996182,  1.80883792, ..., -0.16012815,
         -0.13391878, -0.91439982],
        [-1.21500236, -0.44915012, -0.60759985, ..., -0.16012815,
         -1.18472   ,  0.64956794],
        [ 1.03299487,  0.77904805,  1.00335866, ..., -0.16012815,
          1.26714952, -0.91439982],
        ...,
        [ 1.23370891, -0.27369324,  0.1978794 , ..., -

# Import LogisticRegression model from sklearn library and create a object

In [14]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

# Training model by providing the training data into the model

In [15]:
model.fit(X_train, y_train)

LogisticRegression()

# Predicting the output for the testing set from the model

In [16]:
y_pred = model.predict(X_test)
y_pred

array([1, 0, 0, ..., 0, 0, 0])

In [17]:
y_test

12743    1
11720    0
2433     0
9323     0
8727     0
        ..
1344     1
1611     1
13162    0
11107    0
7529     0
Name: left, Length: 3000, dtype: int64

# Printing metrics of the model

In [18]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

Confusion Matrix: https://en.wikipedia.org/wiki/Confusion_matrix

In [19]:
cm = confusion_matrix(y_test, y_pred)
cm

array([[2110,  164],
       [ 498,  228]])

In [20]:
acc =accuracy_score(y_test, y_pred)
acc

0.7793333333333333